---

- name: install docker
  yum: name=docker-ce state=installed

- name: create the systemd docker options configuration file
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service
  notify:
    - reload systemd
    - restart docker

- meta: flush_handlers

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
